apiVersion: v1
kind: ConfigMap
metadata:
  name: ots-backup
  namespace: default
  labels:
    project: sample
    env: sample
    app: ots-backup
data:
  retentionPeriod: "7" #expects no. of days.
  lastBackup: "1" #expects backup frequecy in days
  collectionName: "XXXXXXXXX" #mongo collection to store backup