apiVersion: v1
kind: Secret
metadata:
  name: ots-backup
  namespace: default
  labels:
    project: sample
    env: sample
    app: ots-backup
data:
  backup-job.json: |
    *** ADD backup.json as BASE64 encrypted ***