apiVersion: v1
kind: Secret
metadata:
  name: ots-restore
  namespace: default
  labels:
    project: sample
    env: sample
    app: ots-backup
data:
  restore-job.json: |
    *** ADD restore.json as BASE64 encrypted ***